elements = {'snapshot_ok_button': ['XPATH', 'html/body/div[3]/form/div[3]/button[1]'],
            'storage_arrow': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]/ul[1]/a[1]'],
            'user_delete_confirm': ['XPATH', ".//*[@id='action-Delete']/div/div[3]/button[2]"],
            'knowledge_base_header_label': ['XPATH',
                                            ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[1]/div/div"],
            'system_menu': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]'],
            'knowledge_base_line1_tab_line9': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[9]"],
            'knowledge_base_subheader_email': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p/a"],
            'cloudbroker_sub_images': ['XPATH', ".//*[@id='collapse-2']/li[5]/a"],
            'intro_line5_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p"],
            'grid_sub_vm': ['XPATH', ".//*[@id='collapse-4']/li[9]/a"],
            'knowledge_base_line7_tab_line3': ['XPATH',".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[3]"],
            'knowledge_base_line1_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[1]"],
            'first_machine_storage': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[1]/td[6]"],
            'users': ['XPATH', ".//*[@id='collapse-2']/li[8]/a"], 'knowledge_base_line5_tab_image7': ['XPATH',
                                                                                                      ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[16]/img"],
            'knowledge_base_line1_tab_line11': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[11]"],
            'knowledge_base_line6_tab_image6': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[12]/img"],
            'cloudbroker_sub_stacks': ['XPATH', ".//*[@id='collapse-2']/li[4]/a"],
            'first_snapshot_rollback': ['XPATH', ".//*[@id='snapshots']/div/table/tbody/tr[1]/td[3]/a[1]/i"],
            'cloudspace_line3_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p"],
            'ec_table_header1': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[1]'], 'knowledge_base_line6_tab_line9': ['XPATH',
                                                                                  ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[17]"],
            'home_button': ['XPATH', ".//*[@id='navbar-list']/ul[1]/li[1]/a"],
            'grid_sub_logs': ['XPATH', ".//*[@id='collapse-4']/li[6]/a"],
            'machines_menu': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[1]/ul/li[1]/ul/li[1]/a"],
            'knowledge_base_line3_tab_line9': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[15]"],
            'knowledge_base_line3_tab_line11': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[19]"],
            'cloudapi_images_show': ['XPATH', ".//*[@id='endpointListTogger_cloudapi__images']"],
            'password': ['XPATH', ".//*[@id='createuser']/div/div[2]/div[3]/div[3]/input"],
            'account_first_id': ['XPATH', ".//*[@id='table_cloudbroker_account']/tbody/tr[1]/td[1]/a"],
            'image_first_id': ['XPATH', ".//*[@id='table_cloudbroker_image']/tbody/tr/td[2]"],
            'knowledge_base_line3_tab_image5': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[9]/img"],
            'knowledge_base_line5_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'machine_description_admin': ['XPATH', ".//*[@id='createmachine']/div/div[2]/div[3]/div[2]/input"],
            'knowledge_base_line3_tab_line10': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[17]"],
            'account_table_first_element': ['XPATH', ".//*[@id='table_cloudbroker_account']/tbody/tr[1]/td[2]"],
            'cloud_space_user_name': ['XPATH', ".//*[@id='create_space']/div/div[2]/div[3]/div[2]/input"],
            'account_enable': ['LINK_TEXT', 'Enable'],
            'virtual machine search': ['XPATH', ".//*[@id='table_cloudbroker_vmachine_filter']/label/input"],
            'cloud_spaces': ['XPATH', ".//*[@id='collapse-2']/li[2]/a"],
            'cloud_space_table_first_element_1': ['XPATH', ".//*[@id='table_cloudbroker_cloudspace']/tbody/tr/td[1]/a"],
            'system_sub_api': ['XPATH', ".//*[@id='collapse-6']/li[7]/a"], 'knowledge_base_line5_tab_image1': ['XPATH',
                                                                                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[2]/img"],
            'knowledge_base_line6_tab_image5': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[10]/img"],
            'ec_table_header2': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[2]'],
            'knowledge_base_line5_tab_line3_sub3': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[3]"],
            'cloudbroker_sub_users': ['XPATH', ".//*[@id='collapse-2']/li[8]/a"],
            'account_action_page_items': ['XPATH', 'html/body/div[2]/div/div/table[2]/tbody/tr[%d]/td[2]'],
            'account_delete': ['LINK_TEXT', 'Delete'],
            'ec_table_header6': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[6]'],
            'knowledge_base_line3_tab_line14': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[27]"],
            'error_conditions': ['XPATH', ".//*[@id='collapse-4']/li[2]/a"],
            'status_overview':['XPATH', ".//*[@id='collapse-4']/li[8]/a"],
            'support_button': ['XPATH', ".//*[@id='navbar-list']/ul[2]/li[4]/a"],
            'knowledge_base_line5_tab_image9': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[20]/img"],
            'user_delete': ['XPATH', 'html/body/div[2]/div/div/div[1]/ul/li[2]/a'],
            'account_page_maxmemory': ['XPATH', 'html/body/div[2]/div/div/table[2]/tbody/tr[1]/td[2]'],
            'capture_button': ['XPATH', ".//*[@id='capturekeyboardbutton']"],
            'knowledge_base_line5_tab_image5': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[9]/img"],
            'knowledge_base_line2_tab_line7_image3': ['XPATH',
                                                      ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[3]/img"],
            'knowledge_base_line3_tab_image2': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[4]/img"],
            'accounts': ['XPATH', ".//*[@id='collapse-2']/li[1]/a"],
            'grid_sub_jumpsacale': ['XPATH', ".//*[@id='collapse-4']/li[5]/a"],
            'grid_portal_header1': ['XPATH', 'html/body/div[2]/div/div/ul/li[1]'],
            'user_search': ['XPATH', ".//*[@id='table_system_user_filter']/label/input"],
            'knowledge_base_line6_tab_line2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[3]"],
            'machine_take_snapshot': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[7]/a"],
            'user_name': ['XPATH', 'html/body/div[2]/div/div/h2'], 'knowledge_base_line6_tab_image9': ['XPATH',
                                                                                                       ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[18]/img"],
            'knowledge_base_line6_tab_line4': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[7]"],
            'update_password': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/form/button"],
            'knowledge_base_line5_tab_image6': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[10]/img"],
            'storage_menu': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]'],
            'knowledge_base_line6_tab_line14': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[27]"],
            'knowledge_base_line3_tab_image3': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[6]/img"],
            'cloudbroker_sub_public_nw': ['XPATH', ".//*[@id='collapse-2']/li[6]/a"],
            'username_textbox': ['ID', "username"], 'knowledge_base_line3_tab_image8': ['XPATH',
                                                                                                      ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[18]/img"],
            'virtual_machine_tabkle_first_element_2': ['XPATH',
                                                       ".//*[@id='table_cloudbroker_vmachine']/tbody/tr/td[2]"],
            'system_sub_groups': ['XPATH', ".//*[@id='collapse-6']/li[5]/a"],
            'ec_table_header4': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[4]'],
            'cloud_space_search': ['XPATH', ".//*[@id='table_cloudbroker_cloudspace_filter']/label/input"],
            'machines_line9_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[9]"],
            'knowledge_base_line3_tab_line4': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[8]"],
            'disks_tab': ['XPATH', ".//*[@id='Disks']/a"],
            'machines_tab': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[3]/a"],
            'snapshot_alert_message': ['XPATH', '//html/body/div[3]/div[2]'],
            'machine_disk_list': ['XPATH', ".//*[@id='createmachine']/div/div[2]/div[3]/div[6]/select"],
            'linux': ['LINK_TEXT', "Linux"],
            'logout_button': ['LINK_TEXT', "Logout"],
            'drop_down_menu': ['ID', 'dropdownMenu1'],
            'ays_text': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]/ul[1]/a[2]'],
            'entries_select_option2': ['XPATH', ".//*[@id='table_system_eco_length']/label/select/option[2]"],
            'knowledge_base_line3_tab_line3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[5]"],
            'machine_ipaddress': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[3]/div/div[2]"],
            'account_name': ['XPATH', ".//*[@id='createaccount']/div/div[2]/div[3]/div[1]/input"],
            'knowledge_base_line6_tab_line3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[5]"],
            'cloud_space_name': ['XPATH', ".//*[@id='create_space']/div/div[2]/div[3]/div[1]/input"],
            'knowledge_base_line4_tab_line3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[3]"],
            'snapshot_delete_ok': ['XPATH', 'html/body/div[3]/form/div[3]/button[1]'],
            'knowledge_base_line3_tab_line3_sub3': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[3]"],
            'intro_line3_label': ['XPATH', ".//*[@id='intro']/div[2]/ul/li"],
            'knowledge_base_line1_tab_line6': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[6]"],
            'knowledge_base_line5_tab_line10': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[17]"],
            'end_user_machine_name_table': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[%d]/td[2]/a"],
            'portforward_tab': ['XPATH',
                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/tour/div/ul/li[7]/a"],
            'knowledge_base_line3_tab_line13': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[23]"],
            'knowledge_base_line2_tab_line3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[3]"],
            'knowledge_base_line6_tab_image4': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[8]/img"],
            'destroy_machine_confirm': ['XPATH', 'html/body/div[3]/form/div[3]/button[1]'],
            'first_machine_memory': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[1]/td[4]"],
            'system_sub_code': ['XPATH', ".//*[@id='collapse-6']/li[6]/a"],
            'user_group': ['XPATH', ".//*[@id='createuser']/div/div[2]/div[3]/div[4]/label[%d]"],
            'account_action_edit': ['LINK_TEXT', 'Edit'],
            'cloudbroker_sub_vm': ['XPATH', ".//*[@id='collapse-2']/li[10]/a"],
            'knowledge_base_line3_tab_image7': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[16]/img"],
            'knowledge_base_line4_tab_text1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/code"],
            'knowledge_base_line7_tab_header3': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[2]"],
            'account_delete_confirm': ['XPATH', ".//*[@id='action-Delete']/div/div[3]/button[2]"],
            'cloudspace_spport_link': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p/a"],
            'intro_line2_label': ['XPATH', ".//*[@id='intro']/div[2]/p[2]"],
            'machine_osimage': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[4]/div/div[2]"],
            'user_profile': ['XPATH', ".//*[@id='wrap']/div/tour/div[2]/div/div[1]/div/ul/li[2]/a"],
            'system_sub_users': ['XPATH', ".//*[@id='collapse-6']/li[4]/a"],
            'knowledge_base_line3_tab_header2': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2[2]"],
            'snapshot_alert_ok': ['XPATH', '//html/body/div[3]/div[3]/button'],
            'defense_shield_line2_label': ['XPATH', ".//*[@id='DefenseShield']/div[2]/ol/li[2]"],
            'virtual_machine_table_first_element_2': ['XPATH', ".//*[@id='table_cloudbroker_vmachine']/tbody/tr/td[2]"],
            'current_pw': ['XPATH',
                           ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/form/div[1]/div[1]/input"],
            'knowledge_base_line7_tab_header4': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[3]"],
            'machine_create_template': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[8]/a"],
            'knowledge_base_line7_tab_line2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[2]"],
            'machines_line2_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[2]"],
            'ec_table_header7': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[7]'],
            'ays_sub_templates': ['XPATH', ".//*[@id='collapse-1']/li[2]/a"],
            'cloudbroker_arrow': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[1]'],
            'edit_description_textbox': ['XPATH', '//html/body/div[2]/form/div[2]/div/div/textarea'],
            'machine_credentials': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[5]/div/div[2]"],
            'cloudspace_delete': ['XPATH', 'html/body/div[2]/div/div/div[1]/ul/li[2]/a'],
            'defense_shield_line5_label': ['XPATH', ".//*[@id='DefenseShield']/div[2]/ol/li[5]"],
            'knowledge_base_line2_tab_image5': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[5]/img"],
            'defense_shield_line': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p"],
            'knowledge_base_line3_tab_image4': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[7]/img"],
            'cloudspace_delete_virtual': ['XPATH', 'html/body/div[2]/div/div/div[1]/ul/li[3]/a'],
            'knowledge_base_button': ['XPATH', ".//*[@id='navbar-list']/ul[2]/li[3]/a"],
            'knowledge_base_line6_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[1]"],
            'knowledge_base_line7_tab_header5': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[4]"],
            'knowledge_base_line2_tab_image7': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[7]/img"],
            'knowledge_base_line7_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[1]"],
            'admin_logout_button': ['XPATH', 'html/body/div[1]/div/div[2]/div/ul[2]/li/a'],
            'knowledge_base_line3_tab_header1': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2[1]"],
            'creating_machine_progress_bar': ['XPATH', ".//*[@id='overlay-loader']/div/h2"],
            'console_message_running': ['XPATH', ".//*[@id='console']/div/em"],
            'account_disable': ['LINK_TEXT', 'Disable'],
            'knowledge_base_line3_tab_image10': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[22]/img"],
            'storage_text': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]/ul[1]/a[2]'],
            'intro_tab': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[1]/a"],
            'create_machine_button': ['XPATH', ".//*[@id='singlebutton']"],
            'account_enable_reason': ['XPATH', ".//*[@id='action-Enable']/div/div[2]/div[3]/div/input"],
            'account_first_user_name': ['XPATH', 'html/body/div[2]/div/div/table[3]/tbody/tr/td[1]/a'],
            'destroy_machine': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[11]/a"],
            'send_ctrl/alt/del_button': ['XPATH', ".//*[@id='noVNC_buttons']"],
            'knowledge_base_line2_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'system_sub_spaces': ['XPATH', ".//*[@id='collapse-6']/li[1]/a"],
            'first_machine_name': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[1]/td[2]/a"],
            'sharing_tab': ['XPATH',
                            ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/tour/div/ul/li[6]/a"],
            'knowledge_base_line3_tab_image11': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[24]"],
            'intro_line4_label': ['XPATH', ".//*[@id='intro']/div[2]/p[3]"],
            'grid_sub_ec': ['XPATH', ".//*[@id='collapse-4']/li[2]/a"],
            'ec_entries_info': ['XPATH', ".//*[@id='table_system_eco_info']"],
            'end_user_accounts_list': ['XPATH', ".//*[@id='accordion']/div[%d]/div[1]/h4/a"],
            'knowledge_base_line6_tab_image12': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[24]/img"],
            'knowledge_base_line3_tab_line12': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[21]"],
            'knowledge_base_line5_tab_image3': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[6]/img"],
            'knowledge_base_line6_tab_image1': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[2]/img"],
            'first_snapshot_delete': ['XPATH', ".//*[@id='snapshots']/div/table/tbody/tr/td[3]/a[2]/i"],
            'knowledge_base_line4_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'ec_table_header3': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[3]'],
            'end_user_machine_table': ['ID', "machine_buckets_list"],
            'storage_sub_1': ['XPATH', ".//*[@id='collapse-5']/li/a"], 'knowledge_base_line6_tab_line15': ['XPATH',
                                                                                                           ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[29]"],
            'user_table_first_element': ['XPATH', ".//*[@id='table_system_user']/tbody/tr/td[1]/a"],
            'knowledge_base_line6_tab_image2': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[4]/img"],
            'knowledge_base_line2_tab_line7_sub6': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[6]"],
            'ubuntu_16_04': ['XPATH', ".//*[@id='Linux']/ul/button[3]"], 'knowledge_base_line2_tab_line5': ['XPATH',
                                                                                                            ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[5]"],
            'cloudspace_delete_deployed': ['XPATH', '/html/body/div[2]/div/div/div[1]/ul/li[2]/a'],
            'knowledge_base_line1_tab_line5': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[5]"],
            'knowledge_base_line5_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[1]"],
            'knowledge_base_line2_tab_line7_sub3': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[3]"],
            'cloudspace_delete_reason': ['XPATH', ".//*[@id='action-DeleteCloudSpace']/div/div[2]/div[3]/div/input"],
            'create_cloud_space': ['XPATH', ".//*[@id='create_spaceLabel']"],
            'cloudspace_subheader_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2"],
            'grid_sub_jobs': ['XPATH', ".//*[@id='collapse-4']/li[3]/a"],
            'snapshot_name_textbox': ['XPATH', 'html/body/div[3]/form/div[2]/ul/input'],
            'grid_text': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]/ul[1]/a[2]'],
            'knowledge_base_line2_tab_line7_sub4': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[4]"],
            'knowledge_base_line5_tab_line11': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[19]"],
            'knowledge_base_subheader_label': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p/strong"],
            'defense_shield_subheader_label': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2"],
            'knowledge_base_line2_tab_line7_sub2': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[2]"],
            'knowledge_base_line7_tab_line5': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[5]"],
            'machine_cpu': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[6]/div/div[2]"],
            'intro_spport_link': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p/a"],
            'machine_reboot': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[5]/a"],
            'cloud_broker': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[2]'],
            'first_snapshot_name': ['XPATH', ".//*[@id='snapshots']/div/table/tbody/tr[1]/td[1]"],
            'machines_pic': ['XPATH', 'html/body/div[1]/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div[2]/a/img'],
            'machines_table': ['XPATH', ".//*[@id='tabbable']"],
            'account_page_status': ['XPATH', 'html/body/div[2]/div/div/table[1]/tbody/tr[2]/td[2]'],
            'end_user_cloud_space': ['XPATH', ".//*[@id='%s']/div/ul/li/a"], 'knowledge_base_line3_tab_line8': ['XPATH',
                                                                                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[14]"],
            'support_line_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/a"],
            'account_enable_page': ['XPATH', ".//*[@id='action-EnableLabel']"],
            'system_sub_sc': ['XPATH', ".//*[@id='collapse-6']/li[2]/a"],
            'knowledge_base_line2_tab': ['XPATH', ".//*[@id='docs-index-list']/li[2]/a"],
            'defense_shield_spport_link': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p/a"],
            'getting_started_button': ['XPATH', ".//*[@id='navbar-list']/ul[2]/li[1]/a"],
            'knowledge_base_line6_tab_line8': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[15]"],
            'machine_api_button': ['XPATH', ".//*[@id='navbar-list']/ul[2]/li[2]/a"],
            'grid_arrow': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]/ul[1]/a[1]'],
            'knowledge_base_line2_tab_line10': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[10]"],
            'knowledge_base_line6_tab_image11': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[22]/img"],
            'knowledge_base_line6_tab_line13': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[25]"],
            'knowledge_base_line2_tab_line2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[2]"],
            'knowledge_base_line7_tab_line4': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[4]"],
            'knowledge_base_line6_tab_line6': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[11]"],
            'password_textbox': ['ID', "password"],
            'GAuth_textbox': ['ID', "code"],
            'authorize_button': ['XPATH', ".//*[@translate='user.views.authorize.authorize']"], 'knowledge_base_line3_tab_line6': ['XPATH',
                                                                                                     ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[12]"],
            'knowledge_base_line3_tab_line17': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[31]"],
            'knowledge_base_line6_tab': ['XPATH', ".//*[@id='docs-index-list']/li[6]/a"],
            'knowledge_base_line5_tab_line13': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[23]"],
            'knowledge_base_line3_tab_line5': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[11]"],
            'cloud_space_table_first_element_2': ['XPATH', ".//*[@id='table_cloudbroker_cloudspace']/tbody/tr/td[2]"],
            'image_table_first_element_2': ['XPATH', ".//*[@id='table_cloudbroker_image']/tbody/tr/td[1]/a"],
            'virtual_machine_table_first_element': ['XPATH', ".//*[@id='table_cloudbroker_vmachine']/tbody/tr/td[1]/a"],
            'grid_sub_jq': ['XPATH', ".//*[@id='collapse-4']/li[4]/a"],
            'cloudspace_line1_label': ['XPATH', ".//*[@id='CloudSpace']/div[2]/ol/li[1]"],
            'machines_line1_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[1]"],
            'account_search': ['XPATH', ".//*[@id='table_cloudbroker_account_filter']/label/input"],
            'image_search': ['XPATH', '//*[@id="table_cloudbroker_image_filter"]/label/input'],
            'stack_search': ['XPATH', ".//*[@id='table_cloudbroker_stack_filter']/label/input"],
            'VM_search':['XPATH', ".//*[@id='table_cloudbroker_vmachine_filter']/label/input"],
            'image_table_element_search':['XPATH', ".//*[@id='table_cloudbroker_image']/tfoot/td[%d]/input"],
            'stack_table_element_search':['XPATH', ".//*[@id='table_cloudbroker_stack']/tfoot/td[%d]/input"],
            'VM_table_element_search':['XPATH', ".//*[@id='table_cloudbroker_vmachine']/tfoot/td[%d]/input"],
            'action_purge_select': ['XPATH', ".//*[@id='action-Purge']/div/div[2]/div[3]/div/select"],
            'knowledge_base_line2_tab_line8_sub2': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[2]/li[2]"],
            'knowledge_base_line3_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'intro_header_label': ['XPATH', ".//*[@id='intro']/div[2]/h2"], 'end_user_create_machine_page': ['XPATH',
                                                                                                             ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/h1"],
            'knowledge_base_line6_tab_image8': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[16]/img"],
            'cloudbroker_sub_sr': ['XPATH', ".//*[@id='collapse-2']/li[11]/a"],
            'cloudbroker_sub_sv': ['XPATH', ".//*[@id='collapse-2']/li[12]/a"],
            'windows_2012': ['XPATH', ".//*[@id='Windows']/ul/button"], 'machine_description_': ['XPATH',
                                                                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[2]/textarea"],
            'machines_line11_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p"],
            'cloudpsace_menu': ['XPATH', ".//*[@id='drop1']/span"], 'cloudapi_images_list_tryit': ['XPATH',
                                                                                                   ".//*[@id='cloudapi__images_post_cloudapi_images_list_content']/form/div[2]/input"],
            'add_virtual_machine': ['XPATH', 'html/body/div[2]/div/div/a[3]'],
            'cloudspace_header_label': ['XPATH', ".//*[@id='CloudSpace']/div[2]/h2"],
            'knowledge_base_line6_tab_line11': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[21]"],
            'console_ipaddress': ['XPATH', ".//*[@id='console']/div/div[2]/div[1]/p"],
            'account_disable_page': ['XPATH', ".//*[@id='action-DisableLabel']"], 'new_pw_1': ['XPATH',
                                                                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/form/div[1]/div[2]/input"],
            'machine_stop': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[4]/a"],
            'ALL_option': ['XPATH', ".//*[@id='action-Purge']/div/div[2]/div[3]/div/select/option[1]"],
            'defense_shield_button': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[1]/div//ul/li[2]/a"],
            'cloudapi_images_list_body': ['XPATH',
                                          ".//*[@id='cloudapi__images_post_cloudapi_images_list_content']/div[3]/div[2]/pre/code"],
            'cloudspace_page_status': ['XPATH', 'html/body/div[2]/div/div/table[1]/tbody/tr[6]/td[2]'],
            'knowledge_base_line6_tab_line10': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[19]"],
            'grid_sub_gn': ['XPATH', ".//*[@id='collapse-4']/li[7]/a"],
            'edit_description_cancel': ['XPATH', '//html/body/div[2]/form/div[3]/button[2]'],
            'knowledge_base_line1_tab_line10': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[10]"],
            'machines_subheader_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2"],
            'knowledge_base_line7_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'knowledge_base_line7_tab_line5_link': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[5]/a"],
            'user_action': ['XPATH', 'html/body/div[2]/div/div/div[1]/button'],
            'knowledge_base_line1_tab_line12': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[12]"],
            'knowledge_base_line2_tab_line8_sub3': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[2]/li[3]"],
            'left_menu': ['CLASS_NAME', 'portals-list', 0],
            'knowledge_base_line1_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'package': ['XPATH',
                          ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div/div/ul/li[%d]/a"],
            'virtual_machine_delete_reason': ['XPATH', ".//*[@id='action-Delete']/div/div[2]/div[3]/div/input"],
            'machine_resume': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[2]/a"],
            'end_user_machine_table_row': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[%d]/td[%d]"],
            'machine_memory': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[7]/div/div[2]"],
            'cloudbroker_menu': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]'],
            'machine_status': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[2]/div/div[2]"],
            'knowledge_base_line5_tab_image8': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[18]/img"],
            'windows': ['LINK_TEXT', "windows"],
            'add_account': ['XPATH', 'html/body/div[2]/div/div/a'], 'knowledge_base_line5_tab_line8': ['XPATH',
                                                                                                       ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[14]"],
            'ec_table_row': ['XPATH', ".//*[@id='table_system_eco']/tbody/tr[1]"],
            'knowledge_base_line4_tab': ['XPATH', ".//*[@id='docs-index-list']/li[4]/a"],
            'machines_line8_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[8]"],
            'defense_shield_line3_label': ['XPATH', ".//*[@id='DefenseShield']/div[2]/ol/li[3]"],
            'knowledge_base_line2_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[1]"],
            'knowledge_base_line3_tab_image12': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[25]"],
            'knowledge_base_line4_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[1]"],
            'knowledge_base_line3_tab_line3_sub1': ['XPATH',".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[1]"],
            'Ubuntu 16.04 x64': ['XPATH', "//button[contains(.,'Ubuntu 16.04 x64')]"],
            'Ubuntu 14.04 x64': ['XPATH', "//button[contains(.,'Ubuntu 14.04 x64')]"],
            'Windows 2012r2 Standard': ['XPATH', "//button[contains(.,'Windows 2012r2 Standard')]"],
            'knowledge_base_line2_tab_line8': ['XPATH',".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[8]"],
            'defense_shield_header': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'cloudbroker_sub_cs': ['XPATH', ".//*[@id='collapse-2']/li[2]/a"],
            'defense_shield_link': ['LINK_TEXT',"Defense Shield"],
            'virtual_machine_delete': ['XPATH', 'html/body/div[2]/div/div/div[1]/ul/li[4]/a'],
            'knowlege_base_button': ['XPATH', ".//*[@id='navbar-list']/ul[2]/li[3]/a"],
            'cloudapi_images_list_btn': ['XPATH',
                                         ".//*[@id='cloudapi__images_post_cloudapi_images_list']/div[1]/h3/span[1]/a"],
            'grid_sub_so': ['XPATH', ".//*[@id='collapse-4']/li[8]/a"],
            'cloudbroker_sub_accounts': ['XPATH', ".//*[@id='collapse-2']/li[1]/a"], 'machine_name': ['XPATH',
                                                                                                      ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[1]/input"],
            'knowledge_base_line1_tab_line3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[3]"],
            'knowledge_base_line5_tab_line3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[5]"],
            'knowledge_base_line5_tab_line6': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[12]"],
            'machines_header_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/h2"],
            'entries_select_option1': ['XPATH', ".//*[@id='table_system_eco_length']/label/select/option[1]"],
            'knowledge_base_line7_tab_header2': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[1]"],
            'cloudbroker_sub_groups': ['XPATH', ".//*[@id='collapse-2']/li[9]/a"],
            'add_cloudspace': ['XPATH', 'html/body/div[2]/div/div/a[2]'], 'knowledge_base_line6_tab_line16': ['XPATH',
                                                                                                              ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[30]"],
            'knowledge_base_line1_tab_line4': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[4]"],
            'knowledge_base_line5_tab_image4': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[7]/img"],
            'knowledge_base_line5_tab_line4': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[8]"],
            'login_popup': ['XPATH', 'html/body/div/md-whiteframe/md-toolbar/h2'],
            'account_maxmemory': ['XPATH', ".//*[@id='createaccount']/div/div[2]/div[3]/div[4]/input"],
            'username_table_first': ['XPATH', ".//*[@id='table_system_user']/tbody/tr[1]/td[1]/a"],
            'action_purge_confirm_button': ['XPATH', ".//*[@id='action-Purge']/div/div[3]/button[2]"],
            'knowledge_base_line5_tab_line3_sub1': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[1]"],
            'knowledge_base_line1_tab_line8': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[8]"],
            'machines_label': ['XPATH', 'html/body/div[1]/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div[2]/div'],
            'ubuntu_15_10': ['XPATH', ".//*[@id='Linux']/ul/button[2]"], 'knowledge_base_line3_tab_line2': ['XPATH',
                                                                                                            ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[3]"],
            'add_user': ['XPATH', 'html/body/div[2]/div/div/a'],
            'end_user_home': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div[2]/p/a"],
            'end_user_machines_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div[2]/p/a"],
            'machines_spport_link': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p/a"],
            'end_user_machine_name': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/h1"],
            'actions_tab': ['XPATH', ".//*[@id='actions']/a"],
            'ec_action_button': ['XPATH', 'html/body/div[2]/div/div/div[1]/button'],
            'knowledge_base_line1_tab_line2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[2]"],
            'system_arrow': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]/ul[1]/a[1]'],
            'cloudspace_line2_label': ['XPATH', ".//*[@id='CloudSpace']/div[2]/ol/li[2]"],
            'knowledge_base_line3_tab_line16': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[30]"],
            'snapshot_confirm_message': ['XPATH', 'html/body/div[3]/form/div[2]/div'],
            'knowledge_base_line3_tab_line3_sub2': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[2]"],
            'machines_line3_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[3]"],
            'username': ['XPATH', ".//*[@id='createuser']/div/div[2]/div[3]/div[1]/input"],
            'knowledge_base_line5_tab_line5': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[11]"],
            'machines_button': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[1]/div//ul/li[1]/a"],
            'defense_shield_line1_label': ['XPATH', ".//*[@id='DefenseShield']/div[2]/ol/li[1]"],
            'knowledge_base_line2_tab_image8': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[8]/img"],
            'ays_arrow': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]/ul[1]/a[1]'],
            'create_account': ['XPATH', ".//*[@id='createaccountLabel']"],
            'machines_line4_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[4]"],
            'knowledge_base_line2_tab_line8_sub1': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[2]/li[1]"],
            'knowledge_base_line3_tab': ['XPATH', ".//*[@id='docs-index-list']/li[3]/a"],
            'knowledge_base_line6_tab_image14': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[28]/img"],
            'account_disable_reason': ['XPATH', ".//*[@id='action-Disable']/div/div[2]/div[3]/div/input"],
            'knowledge_base_line2_tab_line9': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[9]"],
            'intro_line1_label': ['XPATH', ".//*[@id='intro']/div[2]/p[1]"],
            'machines_link': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div[2]/p/a"],
            'knowledge_base_line4_tab_line2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[2]"],
            'confirm_add_user': ['XPATH', ".//*[@id='createuser']/div/div[3]/button[2]"],
            'defense_shield_line6_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p"],
            'knowledge_base_line3_tab_image6': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[10]/img"],
            'knowledge_base_line4_tab_text2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h3[3]"],
            'close_button': ['XPATH', "//button[@type='submit']"],
            'ays_sub_service': ['XPATH', ".//*[@id='collapse-1']/li[1]/a"], 'knowledge_base_line6_tab_image7': ['XPATH',
                                                                                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[14]/img"],
            'home': ['XPATH', ".//*[@id='navbar-list']/ul[1]/li[1]/a"], 'knowledge_base_line3_tab_image1': ['XPATH',
                                                                                                            ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[2]/img"],
            'grid_menu': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]'],
            'account_name_value': ['XPATH', 'html/body/div[2]/div/div/h2'],
            'end_user_logout': ['XPATH', ".//*[@id='wrap']/div/tour/div[2]/div/div[1]/div/ul/li[1]/a/span"],
            'knowledge_base_line6_tab_header': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'knowledge_base_line2_tab_line4': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[4]"],
            'machine_memory_list': ['XPATH', ".//*[@id='createmachine']/div/div[2]/div[3]/div[5]/select"],
            'create_virtual_machine_on_cpu_node': ['XPATH', ".//*[@id='createmachineLabel']"],
            'ays_menu_': ['XPATH', ".//*[@id='collapse-1']/li[1]/a"],
            'error_conditions_header1': ['XPATH', 'html/body/div[2]/div/div/ul/li[2]'],
            'system_text': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]/ul[1]/a[2]'],
            'cloudspace_tab': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[2]/a"],
            'first_machine_cpu': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[1]/td[5]"],
            'snapshot_tab': ['XPATH',
                             ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/tour/div/ul/li[4]/a"],
            'knowledge_base_line5_tab_image10': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[22]/img"],
            'knowledge_base_line1_tab': ['XPATH', ".//*[@id='docs-index-list']/li[1]/a"], 'create_machine': ['XPATH',
                                                                                                             ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[7]/button"],
            'account_action_edit_page_confirm': ['XPATH', ".//*[@id='action-Edit']/div/div[3]/button[2]"],
            'defense_shield_line4_label': ['XPATH', ".//*[@id='DefenseShield']/div[2]/ol/li[4]"],
            'snapshot_delete_message': ['XPATH', 'html/body/div[3]/form/div[2]'],
            'knowledge_base_line5_tab_line3_sub2': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[2]"],
            'console_message_halted': ['XPATH', ".//*[@id='console']/div/div[3]/div[2]"],
            'knowledge_base_line5_tab': ['XPATH', ".//*[@id='docs-index-list']/li[5]/a"],
            'knowledge_base_line7_tab': ['XPATH', ".//*[@id='docs-index-list']/li[7]/a"],
            'ec_table_no_data_text': ['XPATH', ".//*[@id='table_system_eco']/tbody/tr/td"],
            'first_machine': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[1]/td[2]/a"],
            'knowledge_base_line5_tab_image2': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[4]/img"],
            'machines_line6_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[6]"],
            'statistics': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[3]/ul/a'],
            'cloudbroker_sub_private_nw': ['XPATH', ".//*[@id='collapse-2']/li[7]/a"],
            'machines_line5_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[5]"],
            'account_action_edit_page_items': ['XPATH', ".//*[@id='action-Edit']/div/div[2]/div[3]/div[%d]/input"],
            'error_conditions_page': ['XPATH', 'html/body/div[2]/div/div/h2'],
            'machine_confirm_button': ['XPATH', ".//*[@id='createmachine']/div/div[3]/button[2]"],
            'end_user_selected_account': ['XPATH', ".//*[@id='drop1']/span"],
            'create_user': ['XPATH', ".//*[@id='createuserLabel']"], 'knowledge_base_line6_tab_line5': ['XPATH',
                                                                                                        ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[9]"],
            'knowledge_base_line2_tab_line7': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[7]"],
            'knowledge_base_line3_tab_line1': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[1]"],
            'left_menu_button': ['ID', "PortalsHamburgerMenu"],
            'edit_description_ok': ['XPATH', '//html/body/div[2]/form/div[3]/button[1]'],
            'entries_select': ['XPATH', ".//*[@id='table_system_eco_length']/label/select"],
            'knowledge_base_line3_tab_line7': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[13]"],
            'machine_storage': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[8]/div/div[2]"],
            'knowledge_base_line1_tab_line7': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[7]"],
            'error_message': ['XPATH', './/*[@id="form-area"]/md-card-content/div/md-input-container[2]/div[2]/div'],
            'error_password_message': ['XPATH', 'html/body/div/md-whiteframe/md-content/form/div[1]/div'],
            'defense_shield_tab': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ul/li[4]/a"],
            'knowledge_base_line6_tab_image10': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[20]/img"],
            'cloud_space_confirm': ['XPATH', ".//*[@id='create_space']/div/div[3]/button[2]"],
            'virtual_machine_page_status': ['XPATH', 'html/body/div[2]/div/div/table[1]/tbody/tr[13]/td[2]'],
            'knowledge_base_line6_tab_image13': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[26]/img"],
            'disk_size': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div/ul/li[%d]/button"],
            'profile': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'defense_shield_label': ['CLASS_NAME', "padding-right-none", 1],
            'defense_shield_button1': ['CLASS_NAME', "btn", 0],
            'knowledge_base_line5_tab_line7': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[13]"],
            'knowledge_base_line2_tab_line7_sub1': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[1]"],
            'knowledge_base_line6_tab_line12': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[23]"],
            'machine_name_admin': ['XPATH', ".//*[@id='createmachine']/div/div[2]/div[3]/div[1]/input"],
            'knowledge_base_line3_tab_image9': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[20]/img"],

            'mail': ['XPATH', ".//*[@id='createuser']/div/div[2]/div[3]/div[2]/input"],
            'machines_line7_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[7]"],
            'ays_menu': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]'],
            'port_forward_menu': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[1]/div//ul/li[1]/ul/li[3]/a"],
            'cloudbroker_sub_locations': ['XPATH', ".//*[@id='collapse-2']/li[3]/a"],
            'end_user': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[7]/ul/a'],
            'username_search': ['XPATH', ".//*[@id='table_system_user_filter']/label/input"],
            'grid_sub_audits': ['XPATH', ".//*[@id='collapse-4']/li[1]/a"],
            'system_sub_pl': ['XPATH', ".//*[@id='collapse-6']/li[8]/a"],
            'account_disable_confirm': ['XPATH', ".//*[@id='action-Disable']/div/div[3]/button[2]"],
            'knowledge_base_line7_tab_header1': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2"],
            'defense_shield_pic': ['XPATH',
                                   ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div[4]/a/img"],
            'create_machine_menu': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[1]/div//ul/li[1]/ul/li[2]/a"],
            'cloudbroker': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[1]'],
            'system_sub_sm': ['XPATH', ".//*[@id='collapse-6']/li[3]/a"],
            'login_button': ['XPATH', "//button[@type='submit']"],
            'purge_button': ['XPATH', 'html/body/div[2]/div/div/div[1]/ul/li/a'],
            'intro_subheader_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h2"],
            'virtual_machine_action': ['XPATH', 'html/body/div[2]/div/div/div[1]/button'],
            'users_page': ['XPATH', 'html/body/div[2]/div/div/h2'],
            'machine_description': ['XPATH', ".//*[@id='createmachine']/div/div[2]/div[3]/div[2]/input"],
            'machine_pause': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[3]/a"],
            'disk_sizes': ['XPATH', '//*[@id="wrap"]/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[6]/div'],
            'packages':   ['XPATH', '//*[@id="wrap"]/div/tour/div[3]/div[2]/div/div/div/div[2]/div/div/div/div[5]/div/div'],
            'new_pw_2': ['XPATH',
                         ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div/form/div[1]/div[3]/input"],
            'console_tab': ['XPATH', ".//*[@id='console']/a"],
            'machines_line10_label': ['XPATH', ".//*[@id='MachineDeck']/div[2]/ol/li[10]"],
            'account_confirm': ['XPATH', ".//*[@id='createaccount']/div/div[3]/button[2]"],
            'account_username': ['XPATH', ".//*[@id='createaccount']/div/div[2]/div[3]/div[2]/input"],
            'error_conditions_header2': ['XPATH', 'html/body/div[2]/div/div/h2'],
            'knowledge_base_line2_tab_image6': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[6]/img"],
            'machine_start': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[1]/a"], 'changelog_tab': ['XPATH',
                                                                                                       ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/tour/div/ul/li[5]/a"],
            'account_enable_confirm': ['XPATH', ".//*[@id='action-Enable']/div/div[3]/button[2]"],
            'knowledge_base_line2_tab_line6': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/li[6]"],
            'cloudspace_action': ['XPATH', 'html/body/div[2]/div/div/div[1]/button'],
            'snapshot_confirm_ok': ['XPATH', 'html/body/div[3]/form/div[3]/button[1]'],
            'access_denied': ['XPATH', 'html/body/div[2]/div/div/div/div/div/h4'],
            'first_machine_status': ['XPATH', ".//*[@id='machine_buckets_list']/tbody[2]/tr[1]/td[1]"],
            'knowledge_base_subheader_text': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p"],
            'support_subheader_label': ['XPATH', ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/h1"],
            'google': ['XPATH', ".//*[@id='lst-ib']"], 'cloudapi_images_list_accountid': ['XPATH',
                                                                                          ".//*[@id='cloudapi__images_post_cloudapi_images_list_content']/form/table/tbody/tr[1]/td[2]/input"],
            'knowledge_base_line3_tab_image14': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[29]/img"],
            'cloudspace_delete_confirm': ['XPATH', ".//*[@id='action-DeleteCloudSpace']/div/div[3]/button[2]"],
            'account_action': ['XPATH', 'html/body/div[2]/div/div/div[1]/button'],
            'machine_reset': ['XPATH', ".//*[@id='actions']/div/div[2]/ul/li[6]/a"],
            'virtual_machine_delete_confirm': ['XPATH', ".//*[@id='action-Delete']/div/div[3]/button[2]"],
            'ec_table_delete_button': ['XPATH', ".//*[@id='table_system_eco']/tfoot/tr/td[1]/button"],
            'ec_table_body': ['XPATH', ".//*[@id='table_system_eco']/tbody"],
            'knowledge_base_line3_tab_image13': ['XPATH',
                                                 ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[26]/img"],
            'account_delete_reason': ['XPATH', ".//*[@id='action-Delete']/div/div[2]/div[3]/div/input"],
            'take_snapshot': ['XPATH', ".//*[@id='snapshots']/a"], 'knowledge_base_line5_tab_line9': ['XPATH',
                                                                                                      ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[15]"],
            'edit_description_button': ['XPATH', ".//*[@id='actions']/div/div[1]/ul/li[1]/div/div[2]/div[1]/em"],
            'system_sub_ao': ['XPATH', ".//*[@id='collapse-6']/li[9]/a"],
            'account_action_edit_page': ['XPATH', ".//*[@id='action-EditLabel']"],
            'ec_table_header5': ['XPATH', '//*[@id="table_system_eco"]/thead/tr/th[5]'],
            'knowledge_base_line5_tab_line2': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[3]"],
            'defense_shield_button2': ['CLASS_NAME', "btn", 1],
            'knowledge_base_line5_tab_line12': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[21]"],
            'knowledge_base_line6_tab_image3': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[6]/img"],
            'knowledge_base_line3_tab_line15': ['XPATH',
                                                ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[28]"],
            'cloudbroker_text': ['XPATH', 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[2]'],
            'defense_shield_header_label': ['XPATH', ".//*[@id='DefenseShield']/div[2]/h2"],
            'machine_list': ['XPATH', ".//*[@id='tabbable']/h1"],
            'no_machines_message':['XPATH', '//*[@id="wrap"]/div/tour/div[3]/div[2]/div/div/div/div[2]/div[1]/div/div/p[1]'],
            'machine_images_list': ['XPATH', ".//*[@id='createmachine']/div/div[2]/div[3]/div[4]/select"],
            'knowledge_base_line6_tab_line7': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/p[13]"],
            'knowledge_base_line2_tab_line7_sub5': ['XPATH',
                                                    ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/ol/ol[1]/li[5]"],
            'knowledge_base_line4_tab_text3': ['XPATH',
                                               ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/div[4]/div[1]/textarea"],
            'confirm_alert':['CLASS_NAME', 'btn-primary', 0],
            'landing_page_login':['CLASS_NAME', 'sm-font',1],
            'Run Healthcheck':['XPATH','/html/body/div[2]/div/div/a'],
            'action-RunHealthcheckLabel':['ID','action-RunHealthCheckLabel'],
            'confirm healthcheck':['XPATH', ".//*[@id='action-RunHealthCheck']/div/div[3]/button[2]"],
            'alert healthcheck':['CLASS_NAME', 'alert', 1],
            'table cloudbroker account':['ID','table_cloudbroker_account'],
            'table cloudbroker account info':['ID','table_cloudbroker_account_info'],
            'account selector':['CLASS_NAME', 'input-sm', 0],
            'cloudspace selector':['NAME', 'table_cloudbroker_cloudspace_length', 0],
            'user selector':['NAME', 'table_system_user_length', 0],
            'VM_table selector':['NAME', 'table_cloudbroker_vmachine_length', 0],
            'pagination':['CLASS_NAME', 'pagination', 0],
            'thead':['TAG_NAME', 'thead', 0],
            'tr':['TAG_NAME', 'tr', 0],
            'td':['TAG_NAME', 'td', -1],
            'datatables-row-ID':['CLASS_NAME', 'datatables-row-ID', 0],
            'table cloudbroker cloudspace':['ID', 'table_cloudbroker_cloudspace'],
            'table cloudbroker cloudspace info':['ID', 'table_cloudbroker_cloudspace_info'],
            'table cloudbroker image':['ID', 'table_cloudbroker_image'],
            'table cloudbroker image info':['ID', 'table_cloudbroker_image_info'],
            'table cloudbroker stack info':['ID', 'table_cloudbroker_stack_info'],
            'table cloudbroker stack':['ID', 'table_cloudbroker_stack'],
            'table system user info':['ID', 'table_system_user_info'],
            'table system user':['ID', 'table_system_user'],
            'table storagerouter':['ID', 'DataTables_Table_0'],
            'table storagerouter info':['ID', 'DataTables_Table_0_info'],
            'table storagerouter length':['NAME', 'DataTables_Table_0_length', 0],
            'table cloudbroker vmachine info':['ID', 'table_cloudbroker_vmachine_info'],
            'table cloudbroker vmachine':['ID', 'table_cloudbroker_vmachine'],
            'account_edit_Name':['NAME', 'name'],
            'account_edit_Max Memory Capacity':['NAME', 'maxMemoryCapacity'],
            'account_edit_Max VDisk Capacity':['NAME', 'maxVDiskCapacity'],
            'account_edit_Max Number of CPU Cores':['NAME', 'maxCPUCapacity'],
            'account_edit_Max External Network Transfer':['NAME', 'maxNetworkPeerTransfer'],
            'account_edit_Max Number of Public IP Addresses':['NAME', 'maxNumPublicIP'],
            'refresh_button':['LINK_TEXT', 'Refresh'],
            'VM_table_pagination':['ID', 'table_cloudbroker_vmachine_paginate'],
            'stack_table_pagination':['ID', 'table_cloudbroker_stack_paginate'],
            'page title':["CLASS_NAME", "title", 0],
            'navigation bar':['CLASS_NAME', 'breadcrumb', 0],
            'storagerouter search':['XPATH', '//*[@id="DataTables_Table_0_filter"]/label/input'],
            'vmachine paginate':['ID','table_cloudbroker_vmachine_paginate'],
            'stack_table_pagination':['ID', 'table_cloudbroker_stack_paginate'],
            'machine_operations_loading':['ID', 'overlay-loader'],
            'create_user_dialog':['ID','createuser'],
            'create_account_dialog':['ID','createaccount'],
            'create_cloudspace_dialog':['ID','create_space'],
            'create_vm_dialog':['ID','createmachine'],

            'delete_user_dialog':['ID','action-Delete'],
            'delete_account_dialog':['ID','action-Delete'],
            'delete_cloudspace_dialog':['ID','action-DeleteCloudSpace'],
            'delete_vm_dialog':['ID','action-Delete'],
            'edit_account_dialog':['ID','action-Edit']
            }
